objects:
  - name: pan
    loader: robocasa
    urdf: pan
    globalScaling: 1.2
    basePosition: 
      - [0.5, -0.3, 0.075]
      - [0.6, -0.3, 0.075]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: false

  - name: food
    loader: ycb
    urdf: 007_tuna_fish_can
    basePosition:
      - [0.5, 0.2, 0.025]
      - [0.5, 0.2, 0.025]
    baseOrientationEuler:
      - [0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.3141592653]
    useFixedBase: false

  - name: microwave
    loader: custom
    urdf: microwave
    basePosition: [0.8, 0.1, 0.175]
    baseOrientationEuler: [0.0, 0.0, 3.141592653589793]
    useFixedBase: true